title: Hongpei Ren's Homepage
page-top-title: Hongpei Ren
top-section-bg-text: 
home-subtitle: Hongpei Ren&ensp;|&ensp;任红锫
site_description: Neuronscience
email: hongpeiren0228@gmail.com
copyright-text: '&copy; Hongpei Ren 2023-2026. All Rights Reserved.'
